### ISSUE TITLE
Help please.

### ISSUE THREAD

**Issue by whatdoyoumean1** [MarmoriPelaa/GTPackCap#2] opened 2020-01-01 21:25 UTC
Hi, could you provide a working run.py because the code doesnt seems correct, its just crashes for me, also whats about real gt packet debugging or its used to be localhost only?

**Comment by whatdoyoumean1** [comment] 2020-01-01 21:26
@MarmoriPelaa

**Comment by MarmoriPelaa** [comment] 2020-01-01 22:36
**What crashes for you?** Growtopia or run.py?
If the run.py closes instantly then it might mean you use Python 2. You have to use Python 3 in order for it to work.
You connect to localhost because you are redirecting the packets through localhost.
It's hard to explain so the connection diagram looks like this:
```
Your local computer | Growtopia Server
--------------------------------------
Client <-> GTPCAP <-> Server
```

**Comment by whatdoyoumean1** [comment] 2020-01-01 22:40
@MarmoriPelaa its not crashing anymore, but i can't literally get in the server, also i have a question why should i change the hosts file if it will redirect me to local server instead of real growtopia.

**Comment by MarmoriPelaa** [comment] 2020-01-01 22:46
The local server is for capturing the packets; when you connect to the local server, the local server connects to the real gt server which means that it redirects the packets from the server to client and vice versa.

**Comment by whatdoyoumean1** [comment] 2020-01-01 22:46
yes but i literally cant connect its stuck on located in server or smth like that

**Comment by MarmoriPelaa** [comment] 2020-01-01 22:48
Is the enetrepeater.exe running? It will not work without that.

**Comment by whatdoyoumean1** [comment] 2020-01-01 22:48
its running

**Comment by MarmoriPelaa** [comment] 2020-01-01 22:54
Ah, I think I know where the problem is.
stop run.py (press ctrl+c) and open it in your text editor. Then find 17091 and replace it with 17125. This is the port number which is incorrect apparently. I'll update it soon. Finally start run.py again. Tell me if that works.

**Comment by whatdoyoumean1** [comment] 2020-01-01 22:56
still stuck.

**Comment by whatdoyoumean1** [comment] 2020-01-01 22:56
located server, connecting...

**Comment by MeNoFade** [comment] 2020-01-01 23:06
@MarmoriPelaa all work for me now, thank you.

**Comment by MarmoriPelaa** [comment] 2020-01-01 23:07
Alright, closing issue...

**Closed by MarmoriPelaa** 2020-01-01 23:07 UTC
